<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="/img/favicon.ico"/>
    {{ get_title() }}
    {{ javascript_include("js/jquery-1.8.3.min.js") }}
    
    {{ javascript_include("js/raphael.js") }}
    {{ javascript_include("js/jquery.enumerable.js") }}
    {{ javascript_include("js/jquery.tufte-graph.js") }}    
    {{ javascript_include("js/script.js") }}
    
	{{ stylesheet_link("css/bootstrap.css") }}
    {{ stylesheet_link("css/style.css") }}
    {{ stylesheet_link("css/tufte-graph.css") }}
</head>

<body>
<div class="container wrapper">
		<div class="masthead">
			<ul class="nav nav-pills pull-right">
				<li {% if app['controller'] == "index" %}class="active"{% endif %}> <a href="/">Главная</a> </li>
            {% if !answered %}
                <li {% if app['controller'] == "poll" and app['action'] == 'answer' %}class="active"{% endif %}> <a href="/poll/answer">Опрос</a> </li>
            {% endif %}
				<li {% if app['controller'] == "poll" and app['action'] == 'results' %}class="active"{% endif %}> <a href="/poll/results">Результаты</a> </li>
			</ul>
			<h3 class="muted">Phalcon Example</h3>
		</div>
        <div class="row-fluid">
        	{{ content() }}
        </div>
    </div>
	<footer class="hidden">
<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t45.6;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet' "+
"border='0' width='31' height='31'><\/a>")
//--></script><!--/LiveInternet-->
    </footer>
</body>
</html>