<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    {{ get_title() }}
	{{ stylesheet_link("css/bootstrap.css") }}
    {{ stylesheet_link("css/style.css") }}
</head>

<body>
<div class="container wrapper">
		<div class="masthead">
			<ul class="nav nav-pills pull-right">
				<li {% if app['controller'] == "index" %}class="active"{% endif %}>{{ link_to('', 'Home') }}</li>
				<li {% if app['controller'] == "poll" and app['action'] == 'answer' %}class="active"{% endif %}>{{ link_to('poll/answer', 'Poll') }}</li>
				<li {% if app['controller'] == "poll" and app['action'] == 'results' %}class="active"{% endif %}>{{ link_to('poll/results', 'Results') }}</li>
			</ul>
			<h3 class="muted">Phalcon Example</h3>
		</div>
        <div class="row-fluid">
        	{{ content() }}
        </div>
    </div>
	
</body>
</html>