<div style="display: inline-block;">

    {{ image( 'public/img/watermark.png', 'class' : 'title-image', 'align' : 'right' ) }}
    <p>
    	Welcome to <br>
    	<h4>THE FASTEST PHP FRAMEWORK</h4>
    </p>
    <p>PhalconPHP is a web framework delivered as a C extension providing high performance and lower resource consumption</p>
    <ul>
        <li><a href="http://phalconphp.com/" target="_blank">Official site</a></li>
        <li><a href="http://phalconphp.com/download" target="_blank">Download page</a></li>
        <li><a href="http://docs.phalconphp.com/en/latest/index.html" target="_blank">Documentation</a></li>
        <li><a href="https://github.com/phalcon/cphalcon/" target="_blank">Github</a></li>
        <li class="li-unstyled"></li>
        <li><a href="https://github.com/phalcon/cphalcon/" target="_blank">This example repo</a></li>
    </ul>

</div>
<div class="align-center"> {{ link_to('poll/answer', 'class' : 'btn btn-success btn-small', 'Go to example') }}</div>