<div style="display: inline-block;">

    {{ image( 'img/watermark.png', 'class' : 'title-image', 'align' : 'right' ) }}
    <p>
    	Позвольте представить<br>
    	<h4>САМЫЙ БЫСТРЫЙ PHP FRAMEWORK</h4>
    </p>
    <p>PhalconPHP MVC фреймворк, поставляемый как C скомпилированный модуль, невероятно повышающий производительность и снижающий затрачиваемые ресурсы.</p>
    <ul>
        <li><a href="http://phalconphp.com/" target="_blank">Официальный сайт</a></li>
        <li><a href="http://phalconphp.com/download" target="_blank">Скачать</a></li>
        <li><a href="http://docs.phalconphp.com/en/latest/index.html" target="_blank">Документация</a></li>
        <li><a href="https://github.com/phalcon/cphalcon/" target="_blank">Github</a></li>
        <li class="li-unstyled"></li>
        <li><a href="https://github.com/phalcon/cphalcon/" target="_blank">Репозиторий этого сайта</a></li>
    </ul>

</div>
<div class="align-center"> {{ link_to('poll/answer', 'class' : 'btn btn-success btn-small', 'Go to example') }}</div>